### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leandromoh** [leandromoh/RecordParser#37]
- [x] remover remnants "Must be member expression" #39 
- [x] add tests for flag enum write/read #42 
- [x] remove unsed code #38
- [ ] provide factory methods to create builder instead of call constructors
- [ ] ToChar bug when space \n \t
- [ ] let trim optional
- [ ] create builder from header
- [ ] discriminate with invalid values on parse
- [ ] maybe expose record parser class
- [ ] suport get invalid index (> column count) return empty instead of throw
